import { createContext, useContext, useState } from 'react';

const translations = {
  zh: {
    // Common
    save: "保存", cancel: "取消", delete: "删除", edit: "编辑", add: "添加",
    search: "搜索", loading: "加载中...", confirm: "确认", close: "关闭",
    clear: "清空", print: "打印", export: "导出", all: "全部",
    actions: "操作", noData: "暂无数据", noResults: "无结果",
    operationFailed: "操作失败", addSuccess: "添加成功", updateSuccess: "更新成功",
    deleteSuccess: "删除成功", deleteFailed: "删除失败", loadFailed: "加载失败",
    deleteConfirm: "确定删除?", fillCompleteInfo: "请填写完整信息",
    // Auth
    username: "用户名", password: "密码", login: "登录", logout: "退出登录",
    // Admin sidebar
    dashboard: "仪表盘", storeManagement: "门店管理", warehouseManagement: "仓库管理",
    productManagement: "商品管理", transferManagement: "调货管理",
    customerManagement: "客户管理", supplierManagement: "供应商",
    purchaseManagement: "采购管理", salesManagement: "销售管理",
    onlineOrders: "网店订单", reports: "报表统计", exchangeRates: "汇率设置",
    paymentSettings: "支付设置", salesReport: "销售报告",
    // Dashboard
    todaySales: "今日销售", onlineOrderTotal: "网店订单", totalProducts: "商品总数",
    pendingOrders: "待处理订单", recentSales: "最近销售", quickActions: "快捷操作",
    // Products
    productCode: "编码", productName: "商品名称", category: "分类",
    unit: "单位", costPrice: "成本价", margin: "利率",
    price1: "价格1", price2: "价格2", price3Box: "价格3(整箱)",
    boxQuantity: "每箱数量", status: "状态", active: "在售", inactive: "下架",
    addProduct: "添加商品", editProduct: "编辑商品", priceSettings: "价格设置",
    marginFormula: "成本 × (1 + 利率%)",
    searchProduct: "搜索商品名称/编码...",
    // Product Import
    importProducts: "导入商品", selectFile: "选择文件",
    supportedFormats: "支持格式", importSuccess: "导入成功",
    importFailed: "导入失败", downloadTemplate: "下载模板",
    importCount: "导入数量", skipDuplicate: "跳过重复", overwriteDuplicate: "覆盖重复",
    duplicateHandling: "重复处理", startImport: "开始导入",
    importing: "导入中...", importResult: "导入结果",
    created: "新增", updated: "更新", skipped: "跳过", failed: "失败",
    // POS
    posTitle: "POS", currency: "币种", shift: "班次",
    startShift: "当班", endShift: "交班", noShift: "未当班",
    shiftSince: "当班开始", salesOrder: "销售单", items: "件",
    products: "商品", quantity: "数量", priceType: "价格类型",
    unitPrice: "单价", amount: "金额", total: "合计",
    checkout: "收款", scanOrSearch: "扫描条码 / 搜索商品名称...",
    box: "整箱", boxes: "箱", pieces: "件",
    paymentMethod: "支付方式", cash: "现金", card: "刷卡",
    received: "收到金额", change: "找零", confirmPayment: "确认收款",
    // Stores
    storeCode: "门店编码", storeName: "门店名称", addStore: "添加门店",
    editStore: "编辑门店", headquarters: "总部", associatedWarehouse: "关联仓库",
    physicalStore: "实体门店", onlineStore: "网店",
    selectWarehouse: "选择仓库",
    // Warehouses
    warehouseCode: "仓库编码", warehouseName: "仓库名称", addWarehouse: "添加仓库",
    setMainWarehouse: "设为总部仓库", inventoryQty: "库存数量",
    reservedQty: "预留数量", availableQty: "可用数量",
    noInventoryData: "暂无库存数据", inventoryList: "库存列表",
    // Customers
    customerCode: "客户编码", customerName: "客户名称", addCustomer: "添加客户",
    searchCustomerPlaceholder: "搜索客户名称、电话...",
    memberLevel: "会员等级", points: "积分", balance: "余额",
    normal: "普通", vip: "VIP",
    // Suppliers
    supplierCode: "供应商编码", supplierName: "供应商名称", addSupplier: "添加供应商",
    contact: "联系人",
    // Purchases
    createPurchaseOrder: "新建采购单", orderNo: "单号", itemCount: "商品数",
    totalAmount: "总金额", createTime: "创建时间",
    receiveGoods: "入库", receivedStatus: "已入库", pendingReceive: "待入库",
    selectSupplier: "选择供应商", selectProduct: "选择商品",
    receiveWarehouse: "入库仓库", createSuccess: "创建成功",
    addItems: "添加商品",
    // Sales
    otherPayment: "其他", completedStatus: "已完成", pendingStatus: "待处理",
    // Transfer
    newTransfer: "新建调货单", sourceWarehouse: "来源仓库",
    targetWarehouse: "目标仓库", product: "商品", transferConfirm: "确认调货",
    inventoryOverview: "各仓库库存概览", transferHistory: "调货记录",
    stock: "库存", time: "时间", source: "来源", target: "目标",
    sameWarehouseError: "来源和目标仓库不能相同",
    transferSuccess: "调货成功", transferFailed: "调货失败",
    // Sales Report
    salesReportTitle: "销售报告", storeFilter: "门店筛选",
    dateFrom: "开始日期", dateTo: "结束日期", generateReport: "生成报告",
    printReport: "打印报告", totalSales: "总销售额", totalOrders: "总订单数",
    totalItems: "总商品数", storeSalesDetail: "分店销售明细",
    productSalesDetail: "商品销售明细", soldQuantity: "售出数量",
    salesAmount: "销售额", topProducts: "热销商品",
    // Shop
    shopTitle: "网上商店", myOrders: "我的订单", addToCart: "加入购物车",
    cart: "购物车", checkoutTitle: "结账", orderSuccess: "下单成功",
    orderLookup: "查询订单", orderNumber: "订单号", phone: "电话",
    shippingInfo: "收货信息", paymentInfo: "支付信息",
    // Online/Offline
    online: "联网", offline: "断网", offlineMode: "断网模式",
    pendingSync: "待同步", syncNow: "立即同步", syncSuccess: "同步成功",
    offlineWarning: "当前处于断网模式，数据将在恢复联网后自动同步",
    // Stores/Warehouses
    location: "地址", type: "类型",
    retail: "零售店", warehouse: "仓库", mainWarehouse: "总仓库",
    // Customers/Suppliers
    name: "名称", contactPhone: "联系电话", email: "邮箱", address: "地址",
    // Purchase
    purchaseOrder: "采购单", supplier: "供应商",
    received_status: "已入库", pending: "待处理",
    // Language
    language: "语言", chinese: "中文", english: "English", spanish: "Español",
    // Extra
    discount: "折扣", orderDetail: "订单明细", shipping: "运费",
    paid: "已付", processing: "处理中", shipped: "已发货", completed: "已完成",
    customer: "客户", date: "日期",
    // New features
    systemSettings: "系统参数", employees: "员工管理", stockAlerts: "库存预警", stockTaking: "库存盘点",
    companyName: "公司名称", taxId: "税号", companyAddress: "公司地址", companyPhone: "公司电话",
    invoiceHeader: "发票抬头", invoiceFooter: "发票底部", printFormat: "打印格式",
    autoPrint: "自动打印", receiptCopies: "打印份数", scannerEnabled: "扫码枪",
    wholesaleEnabled: "批发功能", wholesaleMinQty: "批发起订量", wholesaleDiscount: "批发折扣",
    refund: "退货退款", refundReason: "退货原因", holdOrder: "挂单", recallOrder: "取单",
    dailySettlement: "日结报表", grossProfit: "毛利润", netSales: "净销售",
    permission: "权限", canDiscount: "允许打折", canRefund: "允许退货", maxDiscount: "最大折扣",
    wholesale: "批发", retailMode: "零售模式", wholesaleMode: "批发模式",
    receipt80mm: "80mm小票", receiptA4: "A4发票", printReceipt: "打印",
    bestSellers: "畅销商品", slowSellers: "滞销商品", actualQty: "实际数量", systemQty: "系统数量",
    difference: "差异", enterQty: "输入数量",
    // Exchange Rates
    systemRates: "系统汇率", categoryRates: "部门汇率",
    categoryRateDesc: "配置各部门的独立汇率",
    localSymbol: "本地货币符号", saveRates: "保存汇率", ratesUpdated: "汇率已更新",
    quickConverter: "快速换算", example: "示例",
    // Payment Settings
    bankTransfer: "银行转账", mobilePay: "移动支付",
    bankName: "银行名称", accountNumber: "账户号码",
    accountHolder: "账户持有人", idNumber: "身份证号",
    selectBank: "选择银行", saveSettings: "保存设置", settingsSaved: "设置已保存",
    saveFailed: "保存失败", preview: "预览",
    transferData: "转账信息", mobilePayData: "移动支付信息",
    bank: "银行", account: "账户", holder: "持有人",
    whatsappContact: "WhatsApp联系",
    whatsappNumber: "WhatsApp号码",
    whatsappHint: "输入带国家代码的号码，不加+或空格",
    whatsappEnabled: "客户下单后可通过WhatsApp联系您",
    saving: "保存中...",
    notes: "备注",
    printReceipt80mm: "打印小票", printInvoiceA4: "打印发票",
    printPriceLabels: "打印价格标签", printPreview: "打印预览",
    selectProducts: "选择商品", selectAll: "全选",
    deselectAll: "取消全选", selectedCount: "已选",
    printSelected: "打印选中", time: "时间",
    // Pricing mode
    pricingMode: "外币定价模式",
    pricingLocalBased: "外币价格按本地价格计算",
    pricingLocalDesc: "Bs.价格=进货价×部门汇率, USD=Bs.÷销售汇率（适用黑市汇率）",
    pricingForeignDirect: "外币价格按本身价格",
    pricingForeignDesc: "直接使用商品设定的USD价格（适用央行汇率）",
    dailySettlement: "日结报表", grossProfit: "毛利润",
    refundHistory: "退款记录", categoryManagement: "分类管理",
    categoryRateDesc: "每个分类可设置独立汇率，用于计算Bs.价格",
    systemRates: "系统汇率",
    // New Features Phase 2
    profitAnalysis: "利润分析", revenue: "营业额", cost: "成本", profit: "利润",
    profitMargin: "毛利率", overallMargin: "整体毛利率", totalRevenue: "总营收",
    totalCost: "总成本", totalProfit: "总利润",
    purchaseHistory: "消费记录", totalSpent: "累计消费", orderCount: "订单数",
    addPoints: "充积分", redeemPoints: "兑换积分", topupBalance: "充值", pointsLog: "积分记录",
    balanceLog: "余额记录", earn: "获得", redeem: "兑换", topup: "充值",
    auditLog: "操作日志", action: "操作", targetType: "对象类型", targetId: "对象ID",
    detail: "详情", operator: "操作员",
    promotions: "促销活动", promoName: "活动名称", promoType: "活动类型",
    discount_promo: "折扣", fullReduction: "满减", buyGet: "买赠", flashSale: "限时特价",
    startDate: "开始日期", endDate: "结束日期", minAmount: "最低金额",
    discountValue: "折扣值", addPromotion: "添加活动",
    accountsReceivable: "应收账款", accountsPayable: "应付账款",
    receivable: "应收", payable: "应付", creditor: "欠款方",
    dueDate: "到期日", paidAmount: "已付金额", remainingAmount: "剩余金额",
    markPaid: "收款", addReceivable: "添加应收", addPayable: "添加应付",
    partialPaid: "部分已付",
    dataBackup: "数据备份", exportBackup: "导出备份", backupDesc: "导出全部数据为JSON文件",
    salesTrend: "销售趋势", last7Days: "最近7天", last30Days: "最近30天",
    rolePermissions: "角色权限", admin: "管理员", manager: "店长", cashier: "收银员", staff: "员工",
    marketing: "营销管理",
    exportSalesReport: "导出销售报表", exportInventoryReport: "导出库存报表",
    exporting: "导出中...",
    usePoints: "使用积分", pointsAvailable: "可用积分", pointsEarned: "获得积分",
    pointsDiscount: "积分抵扣", pointsRate: "积分比例", noCustomerNoPoints: "选择客户后可使用积分",
  },
  en: {
    save: "Save", cancel: "Cancel", delete: "Delete", edit: "Edit", add: "Add",
    search: "Search", loading: "Loading...", confirm: "Confirm", close: "Close",
    clear: "Clear", print: "Print", export: "Export", all: "All",
    actions: "Actions", noData: "No data", noResults: "No results",
    operationFailed: "Failed", addSuccess: "Added", updateSuccess: "Updated",
    deleteSuccess: "Deleted", deleteFailed: "Delete failed", loadFailed: "Load failed",
    deleteConfirm: "Confirm delete?", fillCompleteInfo: "Please fill all fields",
    username: "Username", password: "Password", login: "Login", logout: "Logout",
    dashboard: "Dashboard", storeManagement: "Stores", warehouseManagement: "Warehouses",
    productManagement: "Products", transferManagement: "Transfers",
    customerManagement: "Customers", supplierManagement: "Suppliers",
    purchaseManagement: "Purchases", salesManagement: "Sales",
    onlineOrders: "Online Orders", reports: "Reports", exchangeRates: "Exchange Rates",
    paymentSettings: "Payment Settings", salesReport: "Sales Report",
    todaySales: "Today Sales", onlineOrderTotal: "Online Orders", totalProducts: "Products",
    pendingOrders: "Pending Orders", recentSales: "Recent Sales", quickActions: "Quick Actions",
    productCode: "Code", productName: "Product Name", category: "Category",
    unit: "Unit", costPrice: "Cost", margin: "Margin",
    price1: "Price 1", price2: "Price 2", price3Box: "Price 3 (Box)",
    boxQuantity: "Box Qty", status: "Status", active: "Active", inactive: "Inactive",
    addProduct: "Add Product", editProduct: "Edit Product", priceSettings: "Price Settings",
    marginFormula: "Cost x (1 + Margin%)",
    searchProduct: "Search product name/code...",
    importProducts: "Import Products", selectFile: "Select File",
    supportedFormats: "Supported Formats", importSuccess: "Import Success",
    importFailed: "Import Failed", downloadTemplate: "Download Template",
    importCount: "Import Count", skipDuplicate: "Skip Duplicate", overwriteDuplicate: "Overwrite",
    duplicateHandling: "Duplicate Handling", startImport: "Start Import",
    importing: "Importing...", importResult: "Import Result",
    created: "Created", updated: "Updated", skipped: "Skipped", failed: "Failed",
    posTitle: "POS", currency: "Currency", shift: "Shift",
    startShift: "Start Shift", endShift: "End Shift", noShift: "No Shift",
    shiftSince: "Shift since", salesOrder: "Sales Order", items: "items",
    products: "Products", quantity: "Qty", priceType: "Price Type",
    unitPrice: "Unit Price", amount: "Amount", total: "Total",
    checkout: "Checkout", scanOrSearch: "Scan barcode / Search product...",
    box: "Box", boxes: "boxes", pieces: "pcs",
    paymentMethod: "Payment Method", cash: "Cash", card: "Card",
    received: "Received", change: "Change", confirmPayment: "Confirm Payment",
    storeCode: "Store Code", storeName: "Store Name", addStore: "Add Store",
    editStore: "Edit Store", headquarters: "HQ", associatedWarehouse: "Warehouse",
    physicalStore: "Physical Store", onlineStore: "Online Store",
    selectWarehouse: "Select Warehouse",
    warehouseCode: "Warehouse Code", warehouseName: "Warehouse Name", addWarehouse: "Add Warehouse",
    setMainWarehouse: "Set as Main Warehouse", inventoryQty: "Stock Qty",
    reservedQty: "Reserved Qty", availableQty: "Available Qty",
    noInventoryData: "No inventory data", inventoryList: "Inventory List",
    customerCode: "Customer Code", customerName: "Customer Name", addCustomer: "Add Customer",
    searchCustomerPlaceholder: "Search customer name, phone...",
    memberLevel: "Member Level", points: "Points", balance: "Balance",
    normal: "Normal", vip: "VIP",
    supplierCode: "Supplier Code", supplierName: "Supplier Name", addSupplier: "Add Supplier",
    contact: "Contact",
    createPurchaseOrder: "New Purchase Order", orderNo: "Order No.", itemCount: "Items",
    totalAmount: "Total", createTime: "Created",
    receiveGoods: "Receive", receivedStatus: "Received", pendingReceive: "Pending",
    selectSupplier: "Select Supplier", selectProduct: "Select Product",
    receiveWarehouse: "Receiving Warehouse", createSuccess: "Created",
    addItems: "Add Items",
    otherPayment: "Other", completedStatus: "Completed", pendingStatus: "Pending",
    newTransfer: "New Transfer", sourceWarehouse: "Source",
    targetWarehouse: "Destination", product: "Product", transferConfirm: "Confirm Transfer",
    inventoryOverview: "Inventory Overview", transferHistory: "Transfer History",
    stock: "Stock", time: "Time", source: "Source", target: "Target",
    sameWarehouseError: "Source and target cannot be the same",
    transferSuccess: "Transfer Success", transferFailed: "Transfer Failed",
    salesReportTitle: "Sales Report", storeFilter: "Store Filter",
    dateFrom: "From", dateTo: "To", generateReport: "Generate",
    printReport: "Print Report", totalSales: "Total Sales", totalOrders: "Total Orders",
    totalItems: "Total Items", storeSalesDetail: "Store Sales Detail",
    productSalesDetail: "Product Sales Detail", soldQuantity: "Sold Qty",
    salesAmount: "Sales Amount", topProducts: "Top Products",
    shopTitle: "Online Store", myOrders: "My Orders", addToCart: "Add to Cart",
    cart: "Cart", checkoutTitle: "Checkout", orderSuccess: "Order Success",
    orderLookup: "Track Order", orderNumber: "Order No.", phone: "Phone",
    shippingInfo: "Shipping Info", paymentInfo: "Payment Info",
    online: "Online", offline: "Offline", offlineMode: "Offline Mode",
    pendingSync: "Pending Sync", syncNow: "Sync Now", syncSuccess: "Sync Success",
    offlineWarning: "Offline mode - data will sync when connection is restored",
    location: "Location", type: "Type",
    retail: "Retail", warehouse: "Warehouse", mainWarehouse: "Main Warehouse",
    name: "Name", contactPhone: "Phone", email: "Email", address: "Address",
    purchaseOrder: "Purchase Order", supplier: "Supplier",
    received_status: "Received", pending: "Pending",
    language: "Language", chinese: "中文", english: "English", spanish: "Espanol",
    discount: "Discount", orderDetail: "Order Detail", shipping: "Shipping",
    paid: "Paid", processing: "Processing", shipped: "Shipped", completed: "Completed",
    customer: "Customer", date: "Date",
    systemSettings: "System Settings", employees: "Employees", stockAlerts: "Stock Alerts", stockTaking: "Stock Taking",
    companyName: "Company Name", taxId: "Tax ID", companyAddress: "Address", companyPhone: "Phone",
    invoiceHeader: "Invoice Header", invoiceFooter: "Invoice Footer", printFormat: "Print Format",
    autoPrint: "Auto Print", receiptCopies: "Copies", scannerEnabled: "Barcode Scanner",
    wholesaleEnabled: "Wholesale", wholesaleMinQty: "Min Qty", wholesaleDiscount: "Wholesale Discount",
    refund: "Refund", refundReason: "Refund Reason", holdOrder: "Hold", recallOrder: "Recall",
    dailySettlement: "Daily Settlement", grossProfit: "Gross Profit", netSales: "Net Sales",
    permission: "Permission", canDiscount: "Can Discount", canRefund: "Can Refund", maxDiscount: "Max Discount",
    wholesale: "Wholesale", retailMode: "Retail", wholesaleMode: "Wholesale",
    receipt80mm: "80mm Receipt", receiptA4: "A4 Invoice", printReceipt: "Print",
    bestSellers: "Best Sellers", slowSellers: "Slow Sellers", actualQty: "Actual Qty", systemQty: "System Qty",
    difference: "Difference", enterQty: "Enter Qty",
    systemRates: "System Rates", categoryRates: "Category Rates",
    categoryRateDesc: "Configure exchange rate for each category",
    localSymbol: "Local Symbol", saveRates: "Save Rates", ratesUpdated: "Rates Updated",
    quickConverter: "Quick Converter", example: "Example",
    bankTransfer: "Bank Transfer", mobilePay: "Mobile Payment",
    bankName: "Bank Name", accountNumber: "Account Number",
    accountHolder: "Account Holder", idNumber: "ID Number",
    selectBank: "Select Bank", saveSettings: "Save Settings", settingsSaved: "Settings Saved",
    saveFailed: "Save Failed", preview: "Preview",
    transferData: "Transfer Info", mobilePayData: "Mobile Pay Info",
    bank: "Bank", account: "Account", holder: "Holder",
    whatsappContact: "WhatsApp Contact",
    whatsappNumber: "WhatsApp Number",
    whatsappHint: "Enter number with country code, no + or spaces",
    whatsappEnabled: "Customers can contact you via WhatsApp after ordering",
    saving: "Saving...",
    notes: "Notes",
    printReceipt80mm: "Print Receipt", printInvoiceA4: "Print Invoice",
    printPriceLabels: "Price Labels", printPreview: "Print Preview",
    selectProducts: "Select Products", selectAll: "Select All",
    deselectAll: "Deselect All", selectedCount: "Selected",
    printSelected: "Print Selected", time: "Time",
    pricingMode: "Foreign Currency Pricing",
    pricingLocalBased: "Calculate from local price",
    pricingLocalDesc: "Bs.=Cost×Dept.Rate, USD=Bs.÷Sales Rate (black market rate)",
    pricingForeignDirect: "Use direct foreign price",
    pricingForeignDesc: "Use stored USD prices directly (central bank rate)",
    dailySettlement: "Daily Settlement", grossProfit: "Gross Profit",
    refundHistory: "Refund History", categoryManagement: "Categories",
    profitAnalysis: "Profit Analysis", revenue: "Revenue", cost: "Cost", profit: "Profit",
    profitMargin: "Margin", overallMargin: "Overall Margin", totalRevenue: "Total Revenue",
    totalCost: "Total Cost", totalProfit: "Total Profit",
    purchaseHistory: "Purchase History", totalSpent: "Total Spent", orderCount: "Orders",
    addPoints: "Add Points", redeemPoints: "Redeem Points", topupBalance: "Top Up", pointsLog: "Points Log",
    balanceLog: "Balance Log", earn: "Earn", redeem: "Redeem", topup: "Top Up",
    auditLog: "Audit Log", action: "Action", targetType: "Target Type", targetId: "Target ID",
    detail: "Detail", operator: "Operator",
    promotions: "Promotions", promoName: "Name", promoType: "Type",
    discount_promo: "Discount", fullReduction: "Spend & Save", buyGet: "Buy & Get", flashSale: "Flash Sale",
    startDate: "Start Date", endDate: "End Date", minAmount: "Min Amount",
    discountValue: "Discount Value", addPromotion: "Add Promotion",
    accountsReceivable: "Accounts Receivable", accountsPayable: "Accounts Payable",
    receivable: "Receivable", payable: "Payable", creditor: "Creditor",
    dueDate: "Due Date", paidAmount: "Paid", remainingAmount: "Remaining",
    markPaid: "Mark Paid", addReceivable: "Add Receivable", addPayable: "Add Payable",
    partialPaid: "Partial",
    dataBackup: "Data Backup", exportBackup: "Export Backup", backupDesc: "Export all data as JSON",
    salesTrend: "Sales Trend", last7Days: "Last 7 Days", last30Days: "Last 30 Days",
    rolePermissions: "Permissions", admin: "Admin", manager: "Manager", cashier: "Cashier", staff: "Staff",
    marketing: "Marketing",
    exportSalesReport: "Export Sales", exportInventoryReport: "Export Inventory",
    exporting: "Exporting...",
    usePoints: "Use Points", pointsAvailable: "Available", pointsEarned: "Points Earned",
    pointsDiscount: "Points Discount", pointsRate: "Points Rate", noCustomerNoPoints: "Select customer to use points",
  },  es: {
    save: "Guardar", cancel: "Cancelar", delete: "Eliminar", edit: "Editar", add: "Agregar",
    search: "Buscar", loading: "Cargando...", confirm: "Confirmar", close: "Cerrar",
    clear: "Limpiar", print: "Imprimir", export: "Exportar", all: "Todos",
    actions: "Acciones", noData: "Sin datos", noResults: "Sin resultados",
    operationFailed: "Error", addSuccess: "Agregado", updateSuccess: "Actualizado",
    deleteSuccess: "Eliminado", deleteFailed: "Error al eliminar", loadFailed: "Error al cargar",
    deleteConfirm: "Confirmar eliminar?", fillCompleteInfo: "Complete todos los campos",
    username: "Usuario", password: "Contrasena", login: "Iniciar Sesion", logout: "Cerrar Sesion",
    dashboard: "Panel", storeManagement: "Tiendas", warehouseManagement: "Almacenes",
    productManagement: "Productos", transferManagement: "Transferencias",
    customerManagement: "Clientes", supplierManagement: "Proveedores",
    purchaseManagement: "Compras", salesManagement: "Ventas",
    onlineOrders: "Pedidos Online", reports: "Reportes", exchangeRates: "Tipo de Cambio",
    paymentSettings: "Config. Pagos", salesReport: "Reporte de Ventas",
    todaySales: "Ventas Hoy", onlineOrderTotal: "Pedidos Online", totalProducts: "Productos",
    pendingOrders: "Pendientes", recentSales: "Ventas Recientes", quickActions: "Acciones Rapidas",
    productCode: "Codigo", productName: "Nombre", category: "Categoria",
    unit: "Unidad", costPrice: "Costo", margin: "Margen",
    price1: "Precio 1", price2: "Precio 2", price3Box: "Precio 3 (Caja)",
    boxQuantity: "Cant/Caja", status: "Estado", active: "Activo", inactive: "Inactivo",
    addProduct: "Agregar Producto", editProduct: "Editar Producto", priceSettings: "Precios",
    marginFormula: "Costo x (1 + Margen%)",
    searchProduct: "Buscar producto...",
    importProducts: "Importar Productos", selectFile: "Seleccionar Archivo",
    supportedFormats: "Formatos Soportados", importSuccess: "Importacion Exitosa",
    importFailed: "Error de Importacion", downloadTemplate: "Descargar Plantilla",
    importCount: "Cantidad", skipDuplicate: "Omitir Duplicados", overwriteDuplicate: "Sobrescribir",
    duplicateHandling: "Manejo de Duplicados", startImport: "Iniciar Importacion",
    importing: "Importando...", importResult: "Resultado",
    created: "Creados", updated: "Actualizados", skipped: "Omitidos", failed: "Fallidos",
    posTitle: "POS", currency: "Moneda", shift: "Turno",
    startShift: "Iniciar Turno", endShift: "Cerrar Turno", noShift: "Sin Turno",
    shiftSince: "Turno desde", salesOrder: "Orden de Venta", items: "articulos",
    products: "Productos", quantity: "Cant.", priceType: "Tipo Precio",
    unitPrice: "P. Unit.", amount: "Monto", total: "Total",
    checkout: "Cobrar", scanOrSearch: "Escanear codigo / Buscar producto...",
    box: "Caja", boxes: "cajas", pieces: "pzas",
    paymentMethod: "Metodo de Pago", cash: "Efectivo", card: "Tarjeta",
    received: "Recibido", change: "Cambio", confirmPayment: "Confirmar Pago",
    storeCode: "Codigo Tienda", storeName: "Nombre Tienda", addStore: "Agregar Tienda",
    editStore: "Editar Tienda", headquarters: "Casa Matriz", associatedWarehouse: "Almacen",
    physicalStore: "Tienda Fisica", onlineStore: "Tienda Online",
    selectWarehouse: "Seleccione Almacen",
    warehouseCode: "Codigo Almacen", warehouseName: "Nombre Almacen", addWarehouse: "Agregar Almacen",
    setMainWarehouse: "Almacen Principal", inventoryQty: "Cant. Stock",
    reservedQty: "Cant. Reservada", availableQty: "Cant. Disponible",
    noInventoryData: "Sin datos de inventario", inventoryList: "Lista de Inventario",
    customerCode: "Codigo Cliente", customerName: "Nombre Cliente", addCustomer: "Agregar Cliente",
    searchCustomerPlaceholder: "Buscar cliente...",
    memberLevel: "Nivel Membresia", points: "Puntos", balance: "Saldo",
    normal: "Normal", vip: "VIP",
    supplierCode: "Codigo Proveedor", supplierName: "Nombre Proveedor", addSupplier: "Agregar Proveedor",
    contact: "Contacto",
    createPurchaseOrder: "Nueva Orden de Compra", orderNo: "No. Orden", itemCount: "Articulos",
    totalAmount: "Total", createTime: "Creado",
    receiveGoods: "Recibir", receivedStatus: "Recibido", pendingReceive: "Pendiente",
    selectSupplier: "Seleccione Proveedor", selectProduct: "Seleccione Producto",
    receiveWarehouse: "Almacen de Recepcion", createSuccess: "Creado",
    addItems: "Agregar Articulos",
    otherPayment: "Otro", completedStatus: "Completado", pendingStatus: "Pendiente",
    newTransfer: "Nueva Transferencia", sourceWarehouse: "Origen",
    targetWarehouse: "Destino", product: "Producto", transferConfirm: "Confirmar",
    inventoryOverview: "Inventario por Almacen", transferHistory: "Historial",
    stock: "Stock", time: "Fecha", source: "Origen", target: "Destino",
    sameWarehouseError: "Origen y destino no pueden ser iguales",
    transferSuccess: "Transferencia Exitosa", transferFailed: "Error de Transferencia",
    salesReportTitle: "Reporte de Ventas", storeFilter: "Filtrar Tienda",
    dateFrom: "Desde", dateTo: "Hasta", generateReport: "Generar",
    printReport: "Imprimir Reporte", totalSales: "Ventas Totales", totalOrders: "Total Ordenes",
    totalItems: "Total Articulos", storeSalesDetail: "Detalle por Tienda",
    productSalesDetail: "Detalle por Producto", soldQuantity: "Vendidos",
    salesAmount: "Monto", topProducts: "Más Vendidos",
    shopTitle: "Tienda Online", myOrders: "Mis Pedidos", addToCart: "Agregar al Carrito",
    cart: "Carrito", checkoutTitle: "Pagar", orderSuccess: "Pedido Exitoso",
    orderLookup: "Buscar Pedido", orderNumber: "No. Pedido", phone: "Telefono",
    shippingInfo: "Envio", paymentInfo: "Pago",
    online: "En Linea", offline: "Sin Conexion", offlineMode: "Modo Sin Conexion",
    pendingSync: "Pendiente", syncNow: "Sincronizar", syncSuccess: "Sincronizado",
    offlineWarning: "Modo sin conexion - los datos se sincronizaran al reconectar",
    location: "Ubicacion", type: "Tipo",
    retail: "Tienda", warehouse: "Almacen", mainWarehouse: "Almacen Principal",
    name: "Nombre", contactPhone: "Telefono", email: "Correo", address: "Direccion",
    purchaseOrder: "Orden de Compra", supplier: "Proveedor",
    received_status: "Recibido", pending: "Pendiente",
    language: "Idioma", chinese: "中文", english: "English", spanish: "Espanol",
    discount: "Descuento", orderDetail: "Detalle del Pedido", shipping: "Envio",
    paid: "Pagado", processing: "Procesando", shipped: "Enviado", completed: "Completado",
    customer: "Cliente", date: "Fecha",
    systemSettings: "Config. Sistema", employees: "Empleados", stockAlerts: "Alertas Stock", stockTaking: "Inventario Fisico",
    companyName: "Nombre Empresa", taxId: "RIF", companyAddress: "Direccion", companyPhone: "Telefono",
    invoiceHeader: "Encabezado Factura", invoiceFooter: "Pie Factura", printFormat: "Formato Impresion",
    autoPrint: "Auto Imprimir", receiptCopies: "Copias", scannerEnabled: "Escaner",
    wholesaleEnabled: "Mayoreo", wholesaleMinQty: "Cantidad Min.", wholesaleDiscount: "Desc. Mayoreo",
    refund: "Devolucion", refundReason: "Motivo", holdOrder: "Apartar", recallOrder: "Recuperar",
    dailySettlement: "Cierre Diario", grossProfit: "Ganancia Bruta", netSales: "Ventas Netas",
    permission: "Permiso", canDiscount: "Puede Descontar", canRefund: "Puede Devolver", maxDiscount: "Desc. Maximo",
    wholesale: "Mayoreo", retailMode: "Detalle", wholesaleMode: "Mayoreo",
    receipt80mm: "Ticket 80mm", receiptA4: "Factura A4", printReceipt: "Imprimir",
    bestSellers: "Mas Vendidos", slowSellers: "Menos Vendidos", actualQty: "Cant. Real", systemQty: "Cant. Sistema",
    difference: "Diferencia", enterQty: "Ingrese Cant.",
    systemRates: "Tasas del Sistema", categoryRates: "Tasas por Categoria",
    categoryRateDesc: "Configurar tasa de cambio por categoria",
    localSymbol: "Simbolo Local", saveRates: "Guardar Tasas", ratesUpdated: "Tasas Actualizadas",
    quickConverter: "Convertidor Rapido", example: "Ejemplo",
    bankTransfer: "Transferencia Bancaria", mobilePay: "Pago Movil",
    bankName: "Banco", accountNumber: "Numero de Cuenta",
    accountHolder: "Titular de la Cuenta", idNumber: "Cedula",
    selectBank: "Seleccione Banco", saveSettings: "Guardar Config.", settingsSaved: "Config. Guardada",
    saveFailed: "Error al Guardar", preview: "Vista Previa",
    transferData: "Datos Transferencia", mobilePayData: "Datos Pago Movil",
    bank: "Banco", account: "Cuenta", holder: "Titular",
    whatsappContact: "Contacto WhatsApp",
    whatsappNumber: "Numero WhatsApp",
    whatsappHint: "Ingrese numero con codigo de pais, sin + ni espacios",
    whatsappEnabled: "Los clientes podran contactarte por WhatsApp despues de hacer un pedido",
    saving: "Guardando...",
    notes: "Notas",
    printReceipt80mm: "Imprimir Ticket", printInvoiceA4: "Imprimir Factura",
    printPriceLabels: "Etiquetas de Precio", printPreview: "Vista Previa",
    selectProducts: "Seleccionar Productos", selectAll: "Seleccionar Todo",
    deselectAll: "Deseleccionar Todo", selectedCount: "Seleccionados",
    printSelected: "Imprimir Seleccionados", time: "Hora",
    pricingMode: "Modo de Precio en Divisa",
    pricingLocalBased: "Calcular desde precio local",
    pricingLocalDesc: "Bs.=Costo×Tasa Dpto., USD=Bs.÷Tasa Venta (tasa paralela)",
    pricingForeignDirect: "Usar precio directo en divisa",
    pricingForeignDesc: "Usar precios USD almacenados directamente (tasa BCV)",
    dailySettlement: "Cierre Diario", grossProfit: "Ganancia Bruta",
    refundHistory: "Historial de Devoluciones", categoryManagement: "Categorias",
    profitAnalysis: "Analisis de Ganancias", revenue: "Ingresos", cost: "Costo", profit: "Ganancia",
    profitMargin: "Margen", overallMargin: "Margen Global", totalRevenue: "Ingresos Totales",
    totalCost: "Costo Total", totalProfit: "Ganancia Total",
    purchaseHistory: "Historial de Compras", totalSpent: "Total Gastado", orderCount: "Pedidos",
    addPoints: "Agregar Puntos", redeemPoints: "Canjear Puntos", topupBalance: "Recargar", pointsLog: "Historial Puntos",
    balanceLog: "Historial Saldo", earn: "Ganar", redeem: "Canjear", topup: "Recarga",
    auditLog: "Registro de Auditoria", action: "Accion", targetType: "Tipo", targetId: "ID Objetivo",
    detail: "Detalle", operator: "Operador",
    promotions: "Promociones", promoName: "Nombre", promoType: "Tipo",
    discount_promo: "Descuento", fullReduction: "Ahorro", buyGet: "Compra y Lleva", flashSale: "Oferta Flash",
    startDate: "Fecha Inicio", endDate: "Fecha Fin", minAmount: "Monto Minimo",
    discountValue: "Valor Descuento", addPromotion: "Agregar Promocion",
    accountsReceivable: "Cuentas por Cobrar", accountsPayable: "Cuentas por Pagar",
    receivable: "Por Cobrar", payable: "Por Pagar", creditor: "Deudor",
    dueDate: "Fecha Vencimiento", paidAmount: "Pagado", remainingAmount: "Restante",
    markPaid: "Marcar Pagado", addReceivable: "Agregar Cobro", addPayable: "Agregar Pago",
    partialPaid: "Parcial",
    dataBackup: "Respaldo de Datos", exportBackup: "Exportar Respaldo", backupDesc: "Exportar datos como JSON",
    salesTrend: "Tendencia Ventas", last7Days: "Ultimos 7 Dias", last30Days: "Ultimos 30 Dias",
    rolePermissions: "Permisos", admin: "Admin", manager: "Gerente", cashier: "Cajero", staff: "Personal",
    marketing: "Marketing",
    exportSalesReport: "Exportar Ventas", exportInventoryReport: "Exportar Inventario",
    exporting: "Exportando...",
    usePoints: "Usar Puntos", pointsAvailable: "Disponibles", pointsEarned: "Puntos Ganados",
    pointsDiscount: "Descuento Puntos", pointsRate: "Tasa Puntos", noCustomerNoPoints: "Seleccione cliente para usar puntos",
  }
};

const LangContext = createContext();

export const LangProvider = ({ children }) => {
  const [lang, setLang] = useState(localStorage.getItem('app_lang') || 'zh');
  
  const t = (key) => translations[lang]?.[key] || translations['zh'][key] || key;
  
  const changeLang = (newLang) => {
    setLang(newLang);
    localStorage.setItem('app_lang', newLang);
  };

  return (
    <LangContext.Provider value={{ lang, t, changeLang }}>
      {children}
    </LangContext.Provider>
  );
};

export const useLang = () => useContext(LangContext);
export default LangContext;
